# Generated by Django 2.2.1 on 2019-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190522_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
